language: php
php:
 - 5.5

env:
  matrix:
   - DB=MYSQL CORE_RELEASE=3.3

matrix:
  include:
    - php: 5.5
      env: DB=MYSQL CORE_RELEASE=master

before_script:
 - phpenv rehash
 - composer self-update
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/behat-extension:1.0,silverstripe/testsession:dev-master
 - cd ~/builds/ss

script:
 - vendor/bin/phpunit silverstripe-shortlist/tests/
